### ISSUE TITLE
For Linux Python

### ISSUE THREAD

**Issue by proesd** [aldamr01/Komputasi-Parallel#1]
Use Virtual Environment instead of installing a bunch of packages in one PC / Laptop
You will find it helpful when you must switching between version of some packages, and it will avoid you from error in the future
some helpful reading how to make step #5
https://www.pyimagesearch.com/2019/01/30/ubuntu-18-04-install-tensorflow-and-keras-for-deep-learning/

thanks

**Comment by aldamr01** [comment]
my thanks buddy , great reference :+1:
